apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: dprod-n8n
  POSTGRES_PASSWORD: Dpr0d-n8n-P@ssw0rd#
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: dprod-n8n-non-root
  POSTGRES_NON_ROOT_PASSWORD: Dpr0d-n8n-P@ssw0rd#